name: Build & Test

env:
  BUILD_TYPE: Release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ubuntu:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Sources.
      uses: actions/checkout@v2

    - name: Create Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Sources
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: |
        ./bsdiff  bsdiff bspatch patch.0
        ./bspatch bsdiff bspatch2 patch.0
        cmp -s bspatch bspatch2
  windows:
    name: Windows Server 2019
    runs-on: windows-latest

    steps:
    - name: Checkout Sources.
      uses: actions/checkout@v2

    - name: Create Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: echo cmake ${env:GITHUB_WORKSPACE} -DCMAKE_BUILD_TYPE=${env:BUILD_TYPE}

    - name: Build Sources
      working-directory: ${{runner.workspace}}\build
      run: cmake --build .
