name: Build & Test

env:
  BUILD_TYPE: Release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ubuntu:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Create Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Sources
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ./bsdiff bsdiff bspatch patch.bsdiff && ./bspatch bsdiff bspatch_new patch.bsdiff && cmp -s bspatch bspatch_new

  windows:
    name: Windows Server 2019
    runs-on: windows-2019

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      
    - name: Build Dependencies
      run: vcpkg.exe install bzip2:x64-windows

    - name: Create Environment
      run: cmake -E make_directory "${{runner.workspace}}\build"

    - name: Configure CMake
      working-directory: ${{runner.workspace}}\build
      run: cmake "${env:GITHUB_WORKSPACE}" -DCMAKE_BUILD_TYPE="${env:BUILD_TYPE}" -DCMAKE_TOOLCHAIN_FILE="$(Split-Path $(where.exe vcpkg.exe))\scripts\buildsystems\vcpkg.cmake"

    - name: Build Sources
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --config "${env:BUILD_TYPE}"

    - name: Test
      working-directory: ${{runner.workspace}}\build\${{env.BUILD_TYPE}}
      run: |
        ./bsdiff.exe  bsdiff.exe bspatch.exe     patch.bsdiff
        ./bspatch.exe bsdiff.exe bspatch_new.exe patch.bsdiff
        if ((Get-FileHash bspatch.exe).hash -ne (Get-FileHash bspatch2.exe).hash) { exit 1; }
